name: goat_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  flutter_riverpod: ^2.6.1
  intl: ^0.18.1
  uuid: ^4.3.1
  json_annotation: ^4.9.0
  csv: ^5.0.2
  share_plus: ^7.2.0
  path_provider: ^2.1.1
  flutter_image_compress: ^2.1.0
  fl_chart: ^0.63.0
  mobile_scanner: ^4.0.0
  nfc_manager: ^3.3.0
  pdf: ^3.10.0
  mailer: ^6.1.0
  open_filex: ^4.3.4
  qr_flutter: ^4.1.0
  file_picker: 
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master
  url_launcher: ^6.2.3
  go_router: ^13.2.0
  flutter_secure_storage: ^8.1.0
  provider: ^6.1.1
  carousel_slider: ^5.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.3
  flutter_lints: ^2.0.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider_platform_interface: ^2.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

