name: goat_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  uuid: ^4.3.1
  csv: ^5.0.2
  share_plus: ^7.2.0
  path_provider: ^2.1.1
  flutter_image_compress: ^2.1.0
  fl_chart: ^0.66.2
  mobile_scanner: ^4.0.0
  nfc_manager: ^3.3.0
  pdf: ^3.10.0
  mailer: ^6.1.0
  open_filex: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^2.0.1
  path_provider_platform_interface: ^2.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - .env
